# Generated by Django 4.2.2 on 2023-06-18 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='end',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='start',
        ),
        migrations.AddField(
            model_name='task',
            name='timeline',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='flower_data.timeline'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='timeline',
            name='ends_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='starts_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_goal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='flower_data.goal'),
        ),
        migrations.AlterModelTable(
            name='goal',
            table='goal',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
        migrations.AlterModelTable(
            name='timeline',
            table='timeline',
        ),
    ]
